#!/usr/bin/env python3
import sys
import math

#Para calcular o inteiro da hipotenusa ao quadrado do triângulo retângulo com lado a e b, é necessário criar tais variáveis. 
#É importante relembrar que a e b são números inteiros, positivo e ambos menores que 500. 
a = '30'
b = '40'

#Antes de calcular a hipotenusa é necessário verificar se os dados inseridos são do tipo desejado. 
#Para isso, será inserido um controle no código
