#!/usr/bin/env python3

import sys

#Para que seja possível visualizar os comandos é necessário mudar as permissões de um arquivo ou pasta no terminal
#Para isso, basta rodar o seguinte comando: chmod +x relatório_python_05_02.py
#Após isso, é necessário adicionar o comando: ./relatório_python_05_02.py
